package day20inheritance;

public class AnimalRunner {
    public static void main(String[] args) {
        Cat myCat=new Cat();
        myCat.eat();// Animals eat...
        myCat.drink();// Animals drink...
        myCat.meow();// Cats meow

        Dog myDog=new Dog();
        myDog.eat();//Animals eat...
        myDog.drink();//Animals drink...
        myDog.bark();//Dogs bark...

        Bird myBird=new Bird();

        myBird.eat(); // Animals eat...
        myBird.drink();//Animals drink...
        myBird.tweet();//Birds tweet...
    }
}
